name: era_timesheet_app
description: A Flutter app for timesheet management.
version: 1.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  wakelock_plus: ^1.2.8
  flutter_barcode_scanner: ^2.0.0
  http: ^1.2.2
  intl: ^0.19.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
